---

- name: NGINX | INCLUDE CENTOS
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: NGINX | INCLUDE CENTOS
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: NGINX | ENABLE AT STARTUP
  become: true
  service: name=nginx state=started enabled=yes

- name: NGINX | SITES CONFIG DIRS
  become: true
  file: dest=/etc/nginx/{{ item }} state=absent
  with_items:
   - sites-available
   - sites-enabled

- name: NGINX | SITES CONFIG DIRS
  become: true
  file: dest=/etc/nginx/{{ item }} state=directory owner=root mode=0755
  with_items:
   - sites-available.d
   - sites-enabled.d
  notify: reload nginx

- name: NGINX | MAIN CONFIG
  become: true
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx
